### ISSUE TITLE
[FATAL] [1626064086.830131460]: Failed to connect to the VESC, SerialException Failed to open the serial port to the VESC. IO Exception (2):

### ISSUE THREAD

**Issue by gtierrezandres** [Triton-AI/remote_racer#1]
When using the Noetic docker image, I get the following error when trying to `roslaunch vesc_driver vesc_driver_node.launch`:
![Screenshot from 2021-07-11 21-31-28](https://user-images.githubusercontent.com/48335582/125232540-5f98fe80-e2cc-11eb-8fd0-a85894dd0d38.png)

I did a little research and I fount this [article](https://mushr.io/tutorials/workflow/#troubleshooting)
it basically says that it is a hardware issue and the VESC is probably not connected. However, it is connected and I was under the impression that the circuit is properly set up? Here's a drawing of the circuit
![signal-2021-07-11-220307](https://user-images.githubusercontent.com/48335582/125233628-7e989000-e2ce-11eb-9b7a-ae35489c03c2.jpeg)

**Comment by sisaha9** [comment]
The best way to confirm if this is a hardware issue is to just run Dominic's node. It is connecting to the same VESC too just via PyVESC

**Comment by sisaha9** [comment]
It's already installed in the Dockerfile

**Comment by gtierrezandres** [comment]
When I run Dominic's code I get the following error even though all of the files have permissions:
![Screenshot from 2021-07-12 06-59-39](https://user-images.githubusercontent.com/48335582/125300726-d14b6980-e319-11eb-84d0-d95abff2d59a.png)

**Comment by gtierrezandres** [comment]
I get this error when I try to run the launch file. 
![Screenshot from 2021-07-12 06-59-39](https://user-images.githubusercontent.com/48335582/125306852-14f4a200-e31f-11eb-9fc1-83430a39921a.png)

However, I tried running the individual python file and it worked and I was able to publish to the vesc_rpm_request

**Comment by gtierrezandres** [comment]
Solved the original issue by changing the port in the launch file parameter back to the original `/dev/ttyACM0` instead of `/dev/sensors/vesc`
